# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Skeleton
tagline:          'A bare bones child theme for PageLines DMS'
description:      'Skeleton is a unassuming child theme for [PageLines DMS](http://pagelines.com), by focusing on simplicity over complexity. It does this by removing all nonessential files, offering a simple structure from which you can build upon.'
url:              http://dannyholt.github.io/skeleton/
baseurl:          /skeleton

author:
  name:           'Danny Holt'
  url:            https://github.com/Dannyholt/

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Dannyholt/skeleton
